# Generated by Django 2.1 on 2020-02-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='归属名称')),
            ],
            options={
                'verbose_name': '分类归属',
                'verbose_name_plural': '分类归属',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='作者名称')),
                ('introduction', models.TextField(blank=True, default='这是一位来自星星的作者', null=True, verbose_name='作者简介')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pupuread/author_img/%Y%m%d', verbose_name='作者头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '小说作者',
                'verbose_name_plural': '小说作者',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('attribution', models.ManyToManyField(blank=True, to='pupuread.Attribution', verbose_name='分类归属')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pupuread.Category', verbose_name='父级ID')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pupuread.Attribution', verbose_name='归属')),
            ],
            options={
                'verbose_name': '小说标签',
                'verbose_name_plural': '小说标签',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='导航名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '导航',
                'verbose_name_plural': '导航',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='推进名称')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='recommend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pupuread.Recommend', verbose_name='推荐'),
        ),
    ]
