# Generated by Django 2.1 on 2020-02-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupuread', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='attribution',
        ),
        migrations.AddField(
            model_name='category',
            name='attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pupuread.Attribution', verbose_name='分类归属'),
        ),
    ]
